// devices

export const GET_DEVICES = 'GET_DEVICES'
export const GET_DEVICE = 'GET_DEVICE'
export const GET_APPS = 'GET_APPS'
export const GET_DEVICE_DETAIL = 'GET_DEVICE_DETAIL'

export const DEVICES_LOADING = 'DEVICES_LOADING'
export const APPS_LOADING = 'APPS_LOADING'

export const ADD_DEVICE = 'ADD_DEVICE'
export const REMOVE_DEVICE = 'REMOVE_DEVICE'
export const UPDATE_DEVICES = 'UPDATE_DEVICES'
export const SELECT_DEVICE = 'SELECT_DEVICE'
export const DEVICE_ERROR = 'DEVICE_ERROR'
export const DEVICE_DETAIL = 'DEVICE_DETAIL'
export const DEVICE_DETAIL_ERROR = 'DEVICE_DETAIL_ERROR'

export const LOADING_APPS = 'LOADING_APPS'
export const UPDATE_APPS = 'UPDATE_APPS'
export const APPS_ERROR = 'APPS_ERROR'

export const LOAD_DEVICES = 'LOAD_DEVICES'
export const LOAD_DEVICE_DETAIL = 'LOAD_DEVICE_DETAIL'
export const DEVICE_DETAIL_LOADING = 'DEVICE_DETAIL_LOADING'
export const LOAD_APPS = 'LOAD_APPS'

export const GET_SOCKET = 'GET_SOCKET'
export const STORE_SOCKET = 'STORE_SOCKET'

export const FINDER_ROOT = 'FINDER_ROOT'

export const HOOK_OBJC = 'HOOK_OBJC'
export const UNHOOK_OBJC = 'UNHOOK_OBJC'
export const IS_OBJC_HOOKED = 'IS_OBJC_HOOKED'
export const HOOK_DYLIB = 'HOOK_DYLIC'
export const UNHOOK_DYLIB = 'UNHOOK_DYLIC'
export const IS_SYMBOL_HOOKED = 'IS_SYMBOL_HOOKED'
export const ALL_HOOKS = 'ALL_HOOKS'
export const DELETE_HOOK = 'DELETE_HOOK'

export const CONSOLE_APPEND = 'CONSOLE_APPEND'
export const CONSOLE_LIST = 'CONSOLE_LIST'
export const CONSOLE_MARK_READ = 'CONSOLE_MARK_READ'
export const CONSOLE_UNREAD = 'CONSOLE_UNREAD'
export const CONSOLE_ACTIVE = 'CONSOLE_ACTIVE'
export const CONSOLE_CLEAR = 'CONSOLE_CLEAR'
export const CONSOLE_RUNNING = 'CONSOLE_RUNNING'

export const PROGRESS = 'PROGRESS'
export const DOWNLOADING = 'DOWNLOADING'
export const SET_DOWNLOAD_TOTAL = 'SET_DOWNLOAD_TOTAL'
export const UPDATE_BYTES = 'UPDATE_BYTES'
export const DOWNLOAD_TOTAL_SIZE = 'DOWNLOAD_TOTAL_SIZE'
export const DOWNLOADED_SIZE = 'DOWNLOADED_SIZE'
